
GENERAL_CONFIG_PATH = 'config/multiprocess.json'
#TOPIC_CONFIG_PATH = 'config/topics.json'
TOPIC_CONFIG_PATH = 'config/topics.json'
CONFIG_PATH = 'config/multiprocess.json'


#CHECK IF CONFIG FILE HAS CHANGED
CONFIG_TIME_CHECK = 60*2

SOCIAL_STREAMER_CONFIG_TIME_CHECK = 60*2
STREAM_COLLECTOR_CONFIG_TIME_CHECK = 60*2

#CHECK IF FILES ARE BEING CREATED
FILE_TIME_CHECK = 60*15
FIRST_FILE_CHECK = True

SOCIAL_STREAMER_FILE_TIME_CHECK = 60*5
SOCIAL_STREAMER_FIRST_FILE_CHECK = True

SOCIAL_STREAMER_FILE_CHECK_COUNT = 3

#CHECK IF CRASHED
CRASH_TIME_CHECK = 60*10

SOCIAL_STREAMER_CRASH_TIME_CHECK = 60*10


#Postponement for 2 hours
STREAM_PROCESSOR_POSTPONE_SECONDS = 60